Repository Together42/nest-backend, pull requests merged in 2024-01, with the labels that each got.

#69 Rotation swagger 적용
  src/rotation/dto/create-registration.dto.ts
  src/rotation/dto/create-rotation.dto.ts
  src/rotation/dto/find-rotation-query.dto.ts
  src/rotation/dto/remove-rotation.dto.ts
  src/rotation/dto/update-rotation.dto.ts
  src/rotation/rotations.controller.ts
Labels: documentation

#71 docs: write users api swagger docs
  src/common/dto/error-response.dto.ts
  src/user/dto/user-info.dto.ts
  src/user/user.controller.ts
Labels: documentation

#74 refactor: modify select option when find today rotation
  src/rotation/rotations.service.ts
Labels: refatoring

#76 ci: 운영 서버 배포
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-main.yml
  README.md
  docker-compose.yml
  src/common/dto/error-response.dto.ts
  src/common/utils.ts
  src/main.ts
  src/rotation/dto/create-registration.dto.ts
  src/rotation/dto/create-rotation.dto.ts
  src/rotation/dto/find-rotation-query.dto.ts
  src/rotation/dto/remove-rotation.dto.ts
  src/rotation/dto/update-rotation.dto.ts
  src/rotation/rotations.controller.ts
  src/rotation/rotations.service.ts
  src/user/dto/user-info.dto.ts
  src/user/user.controller.ts
Labels: deploy

#79 docs: add link describing changes of API and DB
  README.md
Labels: documentation

#81 feat: exception filter and logging
  docker-compose.yml
  src/app.module.ts
  src/auth/auth.service.ts
  src/auth/guard/jwt.guard.ts
  src/auth/strategy/jwt.strategy.ts
  src/batch/batch.service.ts
  src/common/enum/error-message.enum.ts
  src/common/exception-filter/service.exception-filter.ts
  src/common/exception-filter/unknown.exception-filter.ts
  src/common/exception/service.exception.ts
  src/common/exception/unknown.exception.ts
  src/common/interceptor/log.interceptor.ts
  src/holiday/holiday.service.ts
  src/holiday/repository/holiday.repository.ts
  src/meetups/meetup.events-handler.ts
  src/meetups/meetups.service.ts
  src/middleware/google.middleware.ts
  src/rotation/rotations.service.ts
  src/user/repository/user.repository.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: enhancement
